version: "3.8"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: logeyes-zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181

  kafka:
    image: confluentinc/cp-kafka:7.5.0
    container_name: logeyes-kafka
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"     # 외부 접근용 (EC2 퍼블릭 IP:9092)
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      # 내부(컨테이너 ↔ 컨테이너), 외부(PC ↔ EC2)
      KAFKA_LISTENERS: INTERNAL://0.0.0.0:9092,EXTERNAL://0.0.0.0:19092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://kafka:9092,EXTERNAL://<EC2_PUBLIC_IP>:19092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "false"

  redis:
    image: redis:7.2
    container_name: logeyes-redis
    ports:
      - "6379:6379"
    command: [ "redis-server", "--appendonly", "yes" ]

  mysql:
    image: mysql:8.0
    container_name: logdetector-mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: logdetector
      MYSQL_USER: logdetector
      MYSQL_PASSWORD: logdetector1234
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data:
