spring:
  datasource:
    url: jdbc:mysql://mysql:3306/logdetector?useSSL=false&serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: logdetector
    password: logdetector1234

  data:
    redis:
      host: redis
      port: 6379

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: true

  batch:
    jdbc:
      initialize-schema: always

  kafka:
    bootstrap-servers: kafka:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: alert-notifier
      auto-offset-reset: latest

      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer

      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer

        spring.json.trusted.packages: com.logeyes.logdetector
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.logeyes.logdetector.stat.rawlog.dto.RawLogEvent

logging:
  level:
    root: info
    com.logeyes: info   # 운영에서는 debug 끄는 게 좋음

gemini:
  api:
    base-url: https://generativelanguage.googleapis.com
    key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash
    timeout: 10s
