# src/main/resources/application-prod.yml (운영)
spring:
  datasource:
    url: ${SPRING_DATASOURCE_URL}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}

  data:
    redis:
      host: ${SPRING_REDIS_HOST}
      port: ${SPRING_REDIS_PORT}

  jpa:
    hibernate:
      ddl-auto: update     # ⚠️ 운영은 update ❌
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  batch:
    jdbc:
      initialize-schema: never

  kafka:
    bootstrap-servers: ${SPRING_KAFKA_BOOTSTRAP_SERVERS}
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
    consumer:
      group-id: alert-notifier
      auto-offset-reset: latest
      key-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.ErrorHandlingDeserializer
      properties:
        spring.deserializer.key.delegate.class: org.apache.kafka.common.serialization.StringDeserializer
        spring.deserializer.value.delegate.class: org.springframework.kafka.support.serializer.JsonDeserializer
        spring.json.trusted.packages: com.logeyes.logdetector
        spring.json.use.type.headers: false
        spring.json.value.default.type: com.logeyes.logdetector.stat.rawlog.dto.RawLogEvent

logging:
  level:
    root: info
    com.logeyes: info

gemini:
  api:
    base-url: https://generativelanguage.googleapis.com
    key: ${GEMINI_API_KEY}
    model: gemini-2.5-flash
    timeout: 10s
